[phases.build]
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'mkdir -p var/cache var/log',
  'chmod -R 775 var',
  'php bin/console cache:warmup --env=prod'
]

[phases.deploy]
cmds = [
  'php bin/console doctrine:migrations:migrate --no-interaction',
  'chmod -R 775 var'
]